stages:
  - build
  - staging

variables:
  APP_IMAGE: franklinribe/node-app

build:
  tags:
    - kubernetes
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
  script:
    - cd mock-endpoints/
    - docker build --cache-from $APP_IMAGE:latest -t $APP_IMAGE:$CI_COMMIT_SHA -t $APP_IMAGE:latest -f Dockerfile .
    - docker push $APP_IMAGE:latest
    - docker push $APP_IMAGE:$CI_COMMIT_SHA

#.deploy_default: &deploy_default
#  - kustomize build k8s/envs/staging

deploy:
#deploy:staging:
  #before_script:
  #  - apt-get update && apt-get install -y apt-transport-https ca-certificates curl
  #  - curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
  #  - echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  #  - apt-get update && sudo apt-get install -y kubectl
  tags:
    - default
  variables:
    APP_URL: node-app.staging.techchurch.com.br
  stage: staging
  image: k8s.gcr.io/kustomize/kustomize:v3.8.7
  environment:
    name: staging
    url: https://${APP_URL}
  script:
    - cp kustomize /usr/bin/
    - kustomize --help
    - *deploy_default
  allow_failure: false
  needs:
    - build
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: always
